<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2018-11-26 03:07:02',
                'updated_at' => '2018-11-26 03:07:02',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2018-11-26 03:07:02',
                'updated_at' => '2019-05-28 00:50:03',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2018-11-26 03:07:02',
                'updated_at' => '2018-11-26 03:07:02',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2018-11-26 03:07:02',
                'updated_at' => '2018-11-26 03:07:02',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2018-11-26 03:07:02',
                'updated_at' => '2019-05-28 00:50:03',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2018-11-26 03:07:02',
                'updated_at' => '2019-05-25 14:16:48',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2018-11-26 03:07:02',
                'updated_at' => '2019-05-25 14:16:48',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2018-11-26 03:07:02',
                'updated_at' => '2019-05-25 14:16:46',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2018-11-26 03:07:02',
                'updated_at' => '2019-05-25 14:16:46',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2018-11-26 03:07:02',
                'updated_at' => '2019-05-28 00:50:03',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2018-11-26 03:07:05',
                'updated_at' => '2018-12-15 18:36:18',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Produtos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bag',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2018-12-15 18:36:07',
                'updated_at' => '2019-05-28 00:50:03',
                'route' => 'voyager.products.index',
                'parameters' => 'null',
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 2,
                'title' => 'Início',
                'url' => '/',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2018-12-18 02:04:44',
                'updated_at' => '2018-12-18 02:20:23',
                'route' => NULL,
                'parameters' => '',
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 2,
                'title' => 'Sobre nós',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2018-12-18 02:05:31',
                'updated_at' => '2018-12-18 02:58:20',
                'route' => 'about',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 2,
                'title' => 'Produtos',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2018-12-18 02:05:47',
                'updated_at' => '2018-12-18 02:58:21',
                'route' => 'shop',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Categorias',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2018-12-24 11:53:48',
                'updated_at' => '2018-12-24 11:54:01',
                'route' => 'voyager.categorias.index',
                'parameters' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 1,
                'title' => 'Cupoms',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-fire',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2018-12-27 15:07:11',
                'updated_at' => '2018-12-28 15:47:51',
                'route' => 'voyager.cupoms.index',
                'parameters' => 'null',
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Clientes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2018-12-28 15:47:11',
                'updated_at' => '2018-12-28 15:47:47',
                'route' => 'voyager.clientes.index',
                'parameters' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Pedidos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bag',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2018-12-28 15:47:36',
                'updated_at' => '2018-12-28 15:47:51',
                'route' => 'voyager.pedidos.index',
                'parameters' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Sabor',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-pizza',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2019-05-28 00:49:21',
                'updated_at' => '2019-05-28 00:53:47',
                'route' => 'voyager.flavors.index',
                'parameters' => 'null',
            ),
        ));
        
        
    }
}